### ISSUE TITLE
The outdated mod dependency would cause the version mismatch error.

### ISSUE THREAD

**Issue by Calvin-Huang** [iKala/gorm-cli#14]
Here is the error message when the project's `go.mod` mismatch to gorm-cli's gorm version.

```
> gorm-cli db:create_migration change_partner_store_id_typepanic: Open plugin filed. (plugin.Open("./migration/.plugins/connection"): plugin was built with a different version of package gorm.io/gorm/clause)
goroutine 1 [running]:
github.com/iKala/gorm-cli/migrate.NewDB()
        /Users/..../go/pkg/mod/github.com/i!kala/gorm-cli@v0.0.0-20230308011807-f9e560bab2f6/migrate/init_db.go:11 +0x9c
main.main()
        /Users/..../go/pkg/mod/github.com/i!kala/gorm-cli@v0.0.0-20230308011807-f9e560bab2f6/main.go:153 +0xb68
```
You have no choice but refer to this repo and verify the GORM version in the `go.mod`. I believe the project shouldn't stick to the CLI-tool's dependency version. It would be more efficient for me if there were auto-update feature or other method to disregard the underlying effort needed to keep up with the version.

**Comment by oxr463** [comment]
Can you please provide reproduction steps?

**Comment by tkennedy13** [comment]
Same issue. I'm running Go 1.23.2 with Gorm v1.9.16 (latest). All I had to do to reproduce this problem was install gorm-cli, create the .gorm-cli.yaml and run `gorm-cli db:create_migration create_user` or any other gorm-cli command.

```
$ gorm-cli db:create_migration create_user
panic: Open plugin filed. (plugin.Open("./migration/.plugins/connection"): plugin was built with a different version of package gorm.io/gorm/clause)

goroutine 1 [running]:
github.com/iKala/gorm-cli/migrate.NewDB()
        /go/pkg/mod/github.com/i!kala/gorm-cli@v0.0.0-20231019125029-0936e0e62ebc/migrate/init_db.go:11 +0x89
main.main()
        /go/pkg/mod/github.com/i!kala/gorm-cli@v0.0.0-20231019125029-0936e0e62ebc/main.go:153 +0xbda
```
